---
title: Uberla 465 ELISA Processing
shorttitle: Uberla 465 ELISA
from:
- name: Paul Obrecht
email: pobrecht@fredhutch.org
includesummary: yes
summary: ELISA processing for the Uberla 465 study
output: html_document
vignette: >
  %\VignetteIndexEntry{Uberla 465 ELISA QC Report}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

<!--
Program Name: preprocess_elisa.Rmd
Creation Date: 9/28/2017
Full name of author: Paul Obrecht
Project or Protocol: Uberla 465
Purpose or description of program: ELISA data processing
Location of program: git@github.fhcrc.org:VIDD-VISC/Uberla465.git (data-raw/)
Location of input data: git@github.fhcrc.org:VIDD-VISC/Uberla465.git (inst/extdata/)
-->

This report documents the Nussenzweig 446 ELISA data processing.

# Preliminaries
We first source our external functions and global variables, load libraries, and set options.

```{r 'prelim', echo=TRUE, eval=TRUE}
library(data.table)
library(knitr)
library(kableExtra)
sys.source("functions.R", envir=topenv())
sys.source("protocol_specific.R", envir=topenv())
pkgName <- roxygen2:::read.description("../DESCRIPTION")$Package

# -------------------------------------- #
# Read file
if(exists("elisa_qfilename")){
  elisa <- fread(file.path("..", "inst", "extdata", elisa_qfilename))
  elisa_unmod <- copy(elisa)
} else {
  stop("In protocol_specific.R, you must define elisa_qfilename to point to the ELISA file in inst/extdata/.")
}

# rx
setkey(elisa, ptid)
rx <- load("../data/Uberla465_rx.rda")
elisa <- merge(elisa[, group := NULL], Uberla465_rx, all.x = TRUE)
```


# Processing
Elisa requires only changing concentration from character to numeric.
```{r 'processing', echo=TRUE, eval=TRUE}
elisa[, concentration := as.numeric(gsub("<", "", concentration))]

results <- elisa[, .N, .(visit, is.na(concentration), oor_indicator=="<<")]
kableit(results, caption = "Non-missing concentration vs populated oor_indicator")

# output
saveObj("elisa", "elisa")
```

# Summaries
## Quick profile of input file prior to processing:
```{r}
# -------------------------------------- #
# Generate QC report
# -------------------------------------- #

# data profile of input data
dP <- dataProfile(elisa_unmod)
kableit(dP)
```

## Quick profile of output dataset:
```{r}
# data profile of output data
dP <- dataProfile(elisa)
kableit(dP, caption = "Variable population of output dataset")
```

